### ISSUE TITLE
Unable to use with server side rendering

### ISSUE THREAD

**Issue by ijsnow** [ugogo/react-input-verification-code#41]
Thanks for the library!

I'm using this in a nextjs application and found I was getting the following error: 

```
Server Error

TypeError: Cannot read properties of null (reading 'registered')
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

I looked in `index.tsx` and don't see the key `registered` being used so it's might be something to do with the css?

I'm using this workaround but it causes a little jitter on initial load:

```javascript
const [showInput, setShowInput] = useState(true)

useEffect(() => {
  setShowInput(true)
}, [setShowInput])

// ...

{showInput && (
  <ReactInputVerificationCode ... />
)}
```

**Comment by ugogo** [comment]
Hey @ijsnow, thanks for the report!

I was able to reproduce the issue, but can't really understand where the problem comes from 🤔 

After checking the [NextJS example project](https://github.com/vercel/next.js/blob/main/examples/with-emotion/package.json), there should not be any updates to do

The only difference I can see is that they are using the v11 of `@emotion/*` 
```
"@emotion/react": "11.1.1",
"@emotion/styled": "11.0.0",
```

when `react-input-verification-code` is using 
```
"@emotion/core": "^10.0.28",
"@emotion/styled": "^10.0.27",
```

I'll publish an alpha version later today, and if this is not enough I'll migrate everything to `styled-components`

🙏

**Comment by ijsnow** [comment]
Looks like it worked! Thanks!
